# Pull base image depending on the machine name
FROM resin/%%RESIN_MACHINE_NAME%%-debian

# Enable systemd
ENV INITSYSTEM ON

# Install PHP
RUN apt-get update \
	&& apt-get install -yq --no-install-recommends php5-common php5-cgi php5 \
    && rm -rf /var/lib/apt/lists/*

# Define container's working directory
WORKDIR /usr/src/app

# Copy current directory to /usr/src/app
COPY . /usr/src/app

# Run PHP script when container lands on device
CMD ["php", "hello.php"]
