# Pull base image depending on the machine name
FROM resin/%%RESIN_MACHINE_NAME%%-python

# Enable systemd
ENV INITSYSTEM ON

# Install Python
RUN apt-get update && apt-get install -y python \
 && rm -rf /var/lib/apt/lists/*

# Define container's working directory
WORKDIR /usr/src/app

# Copy current directory to /usr/src/app
COPY . /usr/src/app

# Run python script when container lands on device
CMD ["python", "hello.py"]
